import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// sidebars.ts


const sidebars: SidebarsConfig = {
  // Combining both Admin and User guides into the main sidebar
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Admin Guide',
      items: [
        // Admin Guide sidebar items (unchanged from before)
        {
          type: 'doc',
          id: 'admin/Index',
          label: 'Introduction',
        },
        {
          label: 'Installation',
          type: 'category',
          link: {
            type: 'doc',
            id: 'admin/Installation/Index',
          },
          items: [
            {
              type: 'doc',
              id:'admin/Installation/Index'
            },
            {
              type: 'doc',
              id:'admin/Installation/Secrets'
            },
            {
              type: 'category',
              label: 'Cloud Providers',
              link: {
                type: 'doc',
                id: 'admin/Installation/Cloud-Providers/Cloud-Providers',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'admin/Installation/Cloud-Providers',
                },
              ],
            },
            {
              type: 'doc',
              id:'admin/Installation/Configuring-Helm-Install'
            },
            {
              type: 'doc',
              id:'admin/Installation/Dynamic-DNS'
            },
            {
              type: 'doc',
              id:'admin/Installation/Mysql-Operator-Installation'
            },
            {
              type: 'doc',
              id:'admin/Installation/Postgres-Operator-Installation'
            },
            {
              type: 'doc',
              id:'admin/Installation/Observability'
            },
            {
              type: 'doc',
              id:'admin/Installation/Logging'
            },
            {
              type: 'doc',
              id:'admin/Installation/Multi-AZ-For-Volumes'
            },
            {
              type: 'doc',
              id:'admin/Installation/Limitations'
            },
          ],
        },
        {
          type: 'category',
          label: 'Customisation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Customisation',
            },
          ],
        },
        {
          type: 'doc',
          id: 'admin/Observability',
          label: 'Observability',
        },
        {
          type: 'category',
          label: 'Day 2 Operations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Day2',
            },
          ],
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Security',
            },
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Testing',
            },
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Troubleshooting',
            },
          ],
        },
        {
          type: 'doc',
          id: 'admin/FAQ',
          label: 'FAQ',
        },
        {
          type: 'doc',
          id: 'admin/Changelog',
          label: 'Changelog',
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        {
          type: 'doc',
          id: 'user/Index',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: 'user/Managed-Service',
          label: 'Managed Service',
        },
        {
          type: 'doc',
          id: 'user/FAQ',
          label: 'FAQ',
        },
        {
          type: 'category',
          label: 'How-to Guides',
          items: [
            'user/Howto/Deploy-a-Datastore',
            'user/Howto/Datastore-settings',
            'user/Howto/Config-management',
            'user/Howto/Scale-a-Datastore',
            'user/Howto/Promote-a-replica',
            'user/Howto/Restore-backup',
            'user/Howto/Create-Datastore-From-Backup',
            'user/Howto/Upgrade-Lifecycle-mgmt',
            'user/Howto/Database-User-management',
            'user/Howto/Database-Db-management',
            'user/Howto/Firewall',
            'user/Howto/Event-viewer',
            'user/Howto/Terraform-provider',

          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'doc',
              id: 'user/Reference/Datastore-Statuses',
              label: "Datastore Statuses",
            },
            'user/Reference/Glossary',
            {
              type: 'doc',
              id: 'user/Reference/Supported-Databases',
              label: "Supported databases",
            },      
            {
              type: 'category',
              label: 'Observability',
              items: [
                {
                  type: 'category',
                  label: 'Metrics',
                  items: [
                    'user/Reference/Observability/Metrics/Introduction',
                    'user/Reference/Observability/Metrics/MySQL-and-MariaDB',
                    'user/Reference/Observability/Metrics/PostgreSQL',
                    'user/Reference/Observability/Metrics/Redis',
                    'user/Reference/Observability/Metrics/System',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Products',
              items: [
                {
                  type: 'category',
                  label: 'MSSQLServer',
                  items: [
                    'user/Reference/Products/MSSQLServer/overview',
                    'user/Reference/Products/MSSQLServer/configurations',
                    'user/Reference/Products/MSSQLServer/limitations',
                    'user/Reference/Products/MSSQLServer/User-Management',
                  ],
                },
                {
                  type: 'category',
                  label: 'MariaDB',
                  items: [
                    'user/Reference/Products/MariaDb/overview', 
                    'user/Reference/Products/MariaDb/Backup',
                    'user/Reference/Products/MariaDb/restore',
                    'user/Reference/Products/MariaDb/configuration',
                    'user/Reference/Products/MariaDb/Importing-Data',
                    'user/Reference/Products/MariaDb/TSL-Connection',
                    'user/Reference/Products/MariaDb/limitations',
                  ],
                },
                {
                  type: 'category',
                  label: 'MySQL',
                  items: [
                    'user/Reference/Products/MySQL/overview',
                    'user/Reference/Products/MySQL/Backup',
                    'user/Reference/Products/MySQL/restore',
                    'user/Reference/Products/MySQL/configuration',
                    'user/Reference/Products/MySQL/Importing-Data',
                    'user/Reference/Products/MySQL/limitations',
                    'user/Reference/Products/MySQL/TSL-Connection',
                    'user/Reference/Products/MySQL/User-Management',
                  ],
                },
                {
                  type: 'category',
                  label: 'PostgreSQL',
                  items: [
                    'user/Reference/Products/PostgreSQL/backup',
                    'user/Reference/Products/PostgreSQL/configuration',
                    'user/Reference/Products/PostgreSQL/extensions',
                    'user/Reference/Products/PostgreSQL/Importing-Data',
                    'user/Reference/Products/PostgreSQL/limitations',
                    'user/Reference/Products/PostgreSQL/restore',
                  ],
                },
                {
                  type: 'category',
                  label: 'Redis',
                  items: [
                    'user/Reference/Products/Redis/backup',
                    'user/Reference/Products/Redis/configuration',
                    'user/Reference/Products/Redis/User-Management',
                  ],
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Technical',
          items: [
            'user/Technical/API',
            'user/Technical/Terraform',
          ],
        },
      ],
    },
  ],
};

export default sidebars;

