import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// sidebars.ts


const sidebars: SidebarsConfig = {
  // Combining both Admin and User guides into the main sidebar
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Admin Guide',
      items: [
        // Admin Guide sidebar items (unchanged from before)
        {
          type: 'doc',
          id: 'admin/Index',
          label: 'Introduction',
        },
        {
          label: 'Installation',
          type: 'category',
          link: {
            type: 'doc',
            id: 'admin/Installation/Index',
          },
          items: [
            {
              type: 'doc',
              id:'admin/Installation/Index'
            },
            {
              type: 'doc',
              id:'admin/Installation/CloudProviders'
            },
            {
              type: 'doc',
              id:'admin/Installation/Configuring-Helm-Install'
            },
            {
              type: 'doc',
              id:'admin/Installation/DynamicDNS'
            },
            {
              type: 'doc',
              id:'admin/Installation/MysqlOperatorInstallation'
            },
            {
              type: 'doc',
              id:'admin/Installation/PostgresOperatorInstallation'
            },
            {
              type: 'doc',
              id:'admin/Installation/Observability'
            },
            {
              type: 'doc',
              id:'admin/Installation/Logging'
            },
            {
              type: 'doc',
              id:'admin/Installation/MultiAZForVolumes'
            },
            {
              type: 'doc',
              id:'admin/Installation/Limitations'
            },
          ],
        },
        {
          type: 'category',
          label: 'Customisation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Customisation',
            },
          ],
        },
        {
          type: 'doc',
          id: 'admin/Observability',
          label: 'Observability',
        },
        {
          type: 'category',
          label: 'Day 2 Operations',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Day2',
            },
          ],
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Security',
            },
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Testing',
            },
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          items: [
            {
              type: 'autogenerated',
              dirName: 'admin/Troubleshooting',
            },
          ],
        },
        {
          type: 'doc',
          id: 'admin/Changelog',
          label: 'Changelog',
        },
      ],
    },
    {
      type: 'category',
      label: 'User Guide',
      items: [
        {
          type: 'doc',
          id: 'user/Index',
          label: 'Introduction',
        },
        {
          type: 'doc',
          id: 'user/Managed-Service',
          label: 'Managed Service',
        },
        {
          type: 'doc',
          id: 'user/FAQ',
          label: 'FAQ',
        },
        {
          type: 'category',
          label: 'How-to Guides',
          items: [
            'user/Howto/Datastore-settings',
            'user/Howto/Config-management',
            'user/Howto/CreateDatastoreFromBackup',
            'user/Howto/Deploy-a-Datastore',
            'user/Howto/Scale-a-Datastore',
            'user/Howto/Upgrade-Lifecycle-mgmt',
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            'user/Reference/Datastore-Statuses',
            'user/Reference/Glossary',
            'user/Reference/Supported-Databases',
            {
              type: 'category',
              label: 'Observability',
              items: [
                {
                  type: 'category',
                  label: 'Metrics',
                  items: [
                    'user/Reference/Observability/Metrics/Introduction',
                    'user/Reference/Observability/Metrics/MySQL-and-MariaDB',
                    'user/Reference/Observability/Metrics/PostgreSQL',
                    'user/Reference/Observability/Metrics/Redis',
                    'user/Reference/Observability/Metrics/System',
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Products',
              items: [
                {
                  type: 'category',
                  label: 'MSSQLServer',
                  items: [
                    'user/Reference/Products/MSSQLServer/overview',
                    'user/Reference/Products/MSSQLServer/configurations',
                    'user/Reference/Products/MSSQLServer/limitations',
                    'user/Reference/Products/MSSQLServer/usermgmt',
                  ],
                },
                {
                  type: 'category',
                  label: 'MariaDB',
                  items: [
                    'user/Reference/Products/MariaDb/overview', 
                    'user/Reference/Products/MariaDb/Backup',
                    'user/Reference/Products/MariaDb/restore',
                    'user/Reference/Products/MariaDb/configuration',
                    'user/Reference/Products/MariaDb/importing_data',
                    'user/Reference/Products/MariaDb/tls_connection',
                    'user/Reference/Products/MariaDb/limitations',
                  ],
                },
                {
                  type: 'category',
                  label: 'MySQL',
                  items: [
                    'user/Reference/Products/MySQL/overview',
                    'user/Reference/Products/MySQL/Backup',
                    'user/Reference/Products/MySQL/restore',
                    'user/Reference/Products/MySQL/configuration',
                    'user/Reference/Products/MySQL/importing_data',
                    'user/Reference/Products/MySQL/limitations',
                    'user/Reference/Products/MySQL/tls_connection',
                    'user/Reference/Products/MySQL/usermgmt',
                  ],
                },
                {
                  type: 'category',
                  label: 'PostgreSQL',
                  items: [
                    'user/Reference/Products/PostgreSQL/backup',
                    'user/Reference/Products/PostgreSQL/configuration',
                    'user/Reference/Products/PostgreSQL/extensions',
                    'user/Reference/Products/PostgreSQL/importing_data',
                    'user/Reference/Products/PostgreSQL/limitations',
                    'user/Reference/Products/PostgreSQL/restore',
                  ],
                },
                {
                  type: 'category',
                  label: 'Redis',
                  items: [
                    'user/Reference/Products/Redis/backup',
                    'user/Reference/Products/Redis/configuration',
                    'user/Reference/Products/Redis/usermgmt',
                  ],
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Technical',
          items: [
            'user/Technical/API',
            'user/Technical/Terraform',
          ],
        },
      ],
    },
  ],
};

export default sidebars;

